"""Initial migration

Revision ID: 4d0c05aa951d
Revises: 
Create Date: 2025-02-23 16:44:04.398664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0c05aa951d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('max_infected', sa.Float(), nullable=False),
    sa.Column('peak_day', sa.Integer(), nullable=False),
    sa.Column('final_susceptible', sa.Float(), nullable=False),
    sa.Column('final_recovered', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation')
    # ### end Alembic commands ###
