"""initialS, initialI

Revision ID: bccce2417b59
Revises: f251cdc00132
Create Date: 2025-03-08 12:26:24.879693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccce2417b59'
down_revision = 'f251cdc00132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initialS', sa.Integer(), nullable=False, server_default="99"))
        batch_op.add_column(sa.Column('initialI', sa.Integer(), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.drop_column('initialI')
        batch_op.drop_column('initialS')

    # ### end Alembic commands ###
