"""Update Simulation model

Revision ID: ce744c8070ae
Revises: 4d0c05aa951d
Create Date: 2025-03-01 18:09:30.663182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce744c8070ae'
down_revision = '4d0c05aa951d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('v_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('h_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mu', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('D', sa.Float(), nullable=True))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('D')
        batch_op.drop_column('mu')
        batch_op.drop_column('h_rate')
        batch_op.drop_column('v_rate')
        batch_op.drop_column('delta')

    # ### end Alembic commands ###
