"""Initial migration

Revision ID: e8a73c713721
Revises: 
Create Date: 2025-04-06 19:30:46.652644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a73c713721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('N', sa.Integer(), nullable=False),
    sa.Column('initialS', sa.Integer(), nullable=False),
    sa.Column('initialI', sa.Integer(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('v_rate', sa.Float(), nullable=True),
    sa.Column('h_rate', sa.Float(), nullable=True),
    sa.Column('mu', sa.Float(), nullable=True),
    sa.Column('D', sa.Float(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('max_infected', sa.Float(), nullable=False),
    sa.Column('peak_day', sa.Integer(), nullable=False),
    sa.Column('final_susceptible', sa.Float(), nullable=False),
    sa.Column('final_recovered', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation')
    # ### end Alembic commands ###
