"""Update Simulation model

Revision ID: f251cdc00132
Revises: ce744c8070ae
Create Date: 2025-03-08 12:02:50.964635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f251cdc00132'
down_revision = 'ce744c8070ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        op.add_column('simulation', sa.Column('N', sa.Integer(), nullable=False, server_default="100"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.drop_column('N')

    # ### end Alembic commands ###
